"""Checkpoint 16.1: the reference corpus in somnus_content

Revision ID: 0001_reference_corpus
Revises:
Create Date: 2026-09-16

Addendum B §B3's model, in the corpus module's own logical database: corpus
versions, reference documents, their chunks and their scopes. This history is
separate from the report service's own (`migrations/`, `somnus_reporting`) per
build plan §3.9 — different database, different user, different history.

Written by hand rather than autogenerated: no MySQL was reachable from the
machine this was authored on, and a migration nobody can generate is still a
migration somebody has to read.

Two shapes worth noting because they carry rules rather than data:

* `reference_documents.corpus_version_added` / `corpus_version_retired` are both
  nullable and both point at `corpus_versions`. A draft has neither; a published
  document has the first; a retired one has both, and its row stays. That is what
  makes "which documents were live at version N" answerable after the fact.
* `rights_status` is nullable here. §B4 makes it a blocking gate on PUBLISH in
  Checkpoint 16.2, which is a rule about a transition, not a column constraint — a
  draft legitimately has no rights declaration yet.

Reversible per §17: `downgrade` drops exactly the four tables this created, in
foreign-key order. Nothing else in `somnus_content` is touched, and the database
is empty before this runs.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0001_reference_corpus"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "corpus_versions",
        sa.Column("version", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("changelog", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "reference_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("citation", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rights_status", sa.String(length=32), nullable=True),
        sa.Column("rights_evidence", sa.Text(), nullable=True),
        sa.Column("added_by", sa.String(length=36), nullable=False),
        sa.Column("added_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.Column("retired_reason", sa.Text(), nullable=True),
        sa.Column("corpus_version_added", sa.Integer(), nullable=True),
        sa.Column("corpus_version_retired", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["corpus_version_added"], ["corpus_versions.version"]),
        sa.ForeignKeyConstraint(["corpus_version_retired"], ["corpus_versions.version"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reference_document_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", mysql.LONGTEXT(), nullable=True),
        sa.Column("embedded_at", sa.DateTime(), nullable=True),
        sa.Column("embedding_model", sa.String(length=64), nullable=True),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["reference_documents.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunk_position"),
    )
    op.create_table(
        "reference_document_scopes",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["reference_documents.id"]),
        sa.PrimaryKeyConstraint("document_id", "scope_type", "scope_key"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Children first: both reference `reference_documents`, which references
    # `corpus_versions`.
    op.drop_table("reference_document_scopes")
    op.drop_table("reference_document_chunks")
    op.drop_table("reference_documents")
    op.drop_table("corpus_versions")
